### ISSUE TITLE
Blender 4.0 - Addon breaks

### ISSUE THREAD

**Issue by Draise14** [johnnygizmo/asset_snapshot#7]
![image](https://github.com/johnnygizmo/asset_snapshot/assets/35357409/f4254171-fdf9-4f10-8751-5aa75385ba4f)

When using the addon in Blender 4.0.0 builds, there is an issue. There seems to be some breaking API changes that also breaks the addon.

**Comment by Draise14** [comment]
File: `__init__.py`
![image](https://github.com/johnnygizmo/asset_snapshot/assets/35357409/b9a34945-ca43-4719-ad22-33bae9175c39)

**Comment by johnnygizmo** [comment]
Thanks for tackling this!
